# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0002_artical'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artical',
            new_name='Article',
        ),
    ]
