# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0005_article_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_on',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
