# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0007_auto_20171209_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
