# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_news', '0008_auto_20171209_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
